version: '3.5'
services:
  ckan:
    ports:
      - 5000:5000
    volumes:
      - ./ckanext-basedosdados:/app/ckanext-basedosdados
      - ./configs/:/app/configs/
    environment:
    - WERKZEUG_DEBUG_PIN=off
  db:
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
