version: '3'

services:
  next:
    container_name: nextjs
    build:
      context: next
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${NEXT_PORT}:3000
    volumes:
      - ./next:/app
