version: '3'

services:
  next:
    build:
      context: next
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./next:/app
    command: >
      sh -c "yarn install && yarn run dev"
