version: '3.5'
services:
  ckan:
    ports:
      - 5000:5000
    volumes:
      - ./ckanext-basedosdados:/app/ckanext-basedosdados
      - ./vendor/ckan:/ckan
      - ./configs/:/app/configs/
      - ckan_home:/root
    environment:
    - WERKZEUG_DEBUG_PIN=off
    # command: ["gunicorn", "--bind=0.0.0.0:5000", "--workers=1", "--reload", "wsgi"]
    command: "ckan run --host 0.0.0.0 --port 5000 --reloader true"
  db:
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  ckan_home:
