apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.name }}-service
  labels:
    app.kubernetes.io/component: basedosdados-website
    app.kubernetes.io/name: {{ .Values.website.name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/component: basedosdados-website
    app.kubernetes.io/name: {{ .Values.website.name }}
