# Website configuration
website:
  # Deployment name
  name: "basedosdados-website"

  # Deployment image
  image:
    name: "ghcr.io/basedosdados/website"
    tag: "production" # We use the production tag fot the website as a default
    pullPolicy: "Always"

  # Number of replicas
  replicas: 1

  # Specifying resources is recommended for production deployments
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1G
    # requests:
    #   cpu: 100m
    #   memory: 500Mi

  # Additional environment variables to be passed to the website container.
  env: []
    # - name: "SOME_ENV"
    #   value: "some-value"
  envFrom: []
    # - secretRef:
    #     name: "some-secret"

  # Ingress configuration
  ingress:
    # Enable ingress
    enabled: false

    # Host to be used in the ingress
    host: "basedosdados-website.example.com"

    # Ingress annotations
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    # TLS configuration
    tls: []
      # - secretName: basedosdados-website-tls
      #   hosts:
      #     - basedosdados-website.example.com

    internationalDomains:
      - language: "es"
        host: "basedelosdatos-website.example.com"
        annotations: {}
        tls: []
