# Website configuration
website:
  # Deployment name
  name: "basedosdados-website"

  # Deployment image
  image:
    name: "ghcr.io/basedosdados/website"
    tag: "production"
    pullPolicy: "Always"

  # Number of replicas
  replicas: 1

  # Specifying resources is recommended for production deployments
  resources: {}

  # Additional environment variables
  env: []
  envFrom: []

  # Ingress configuration
  ingress:
    enabled: false
    host: ""
    annotations: {}
    tls: []
    internationalDomains: []
